---
- name: Ensure /opt/peoplestrong exists
  file:
    path: /opt/peoplestrong
    state: directory
    owner: <username>
    group: <group>
    mode: '0755'

- name: Copy punch.py script
  ansible.builtin.copy:
    src: files/punch.py
    dest: /opt/peoplestrong/punch.py
    owner: <username>
    group: <group>
    mode: '0644'

- name: Copy requirements.txt
  ansible.builtin.copy:
    src: files/requirements.txt
    dest: /opt/peoplestrong/requirements.txt
    owner: <username>
    group: <group>
    mode: '0644'

- name: Install virtualenv
  ansible.builtin.apt:
    name: virtualenv
    state: latest
    install_recommends: false

- name: Install specified python requirements in indicated (virtualenv)
  ansible.builtin.pip:
    requirements: /opt/peoplestrong/requirements.txt
    virtualenv: /opt/peoplestrong/venv
  become: false